[project]
name = "eva"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prompt-toolkit>=3.0.51",
    "psutil>=7.0.0",
    "scapy>=2.6.1",
    "typer>=0.16.0",
]
